#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jul 13, 2021 11:30:50 AM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 340x315+376+189
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1181
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "TVeSmart switch"
    vTcl:DefineAlias "$top" "TVeSmartAppTopLevel" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab45 \
        -foreground black -text {Arduino Relay controller} \
        -background #d4d4d4 -height 207 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 319 
    vTcl:DefineAlias "$top.lab45" "label_frame_dout" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    set site_3_0 $top.lab45
    button $site_3_0.but55 \
        -activebackground #d4d4d4 -activeforeground #000000 \
        -background #d4d4d4 -borderwidth 0 -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d4d4d4 \
        -highlightcolor black -pady 0 -relief flat -text do1 
    vTcl:DefineAlias "$site_3_0.but55" "button_do1" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    button $site_3_0.but45 \
        -activebackground #d4d4d4 -activeforeground #000000 \
        -background #d4d4d4 -borderwidth 0 -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d4d4d4 \
        -highlightcolor black -pady 0 -relief flat -text do2 
    vTcl:DefineAlias "$site_3_0.but45" "button_do2" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    entry $site_3_0.ent48 \
        -background #d4d4d4 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify center -selectbackground blue \
        -selectforeground white -width 204 
    vTcl:DefineAlias "$site_3_0.ent48" "entry_relay1" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    entry $site_3_0.ent58 \
        -background #d4d4d4 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify center -selectbackground blue \
        -selectforeground white -width 204 
    vTcl:DefineAlias "$site_3_0.ent58" "entry_relay2" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    place $site_3_0.but55 \
        -in $site_3_0 -x 0 -relx 0.752 -y 0 -rely 0.233 -width 60 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.752 -y 0 -rely 0.651 -width 60 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.031 -y 0 -rely 0.233 -width 204 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 0 -relx 0.031 -y 0 -rely 0.651 -width 204 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #008000 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground #ffffff \
        -highlightcolor #000000 -pady 0 -text OPEN 
    vTcl:DefineAlias "$top.but49" "button_com_port_open_close" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {select COM port} 
    vTcl:DefineAlias "$top.lab57" "label_com_port_selection" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    ttk::combobox $top.tCo61 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo61" "combobox_com_port_list" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    label $top.lab46 \
        -activebackground #ffffff -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$top.lab46" "label_com_port_status_info" vTcl:WidgetProc "TVeSmartAppTopLevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.286 -width 0 -relwidth 0.938 \
        -height 0 -relheight 0.683 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.824 -y 0 -rely 0.033 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.018 -y 0 -rely 0.033 -width 0 -relwidth 0.335 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
    place $top.tCo61 \
        -in $top -x 0 -relx 0.382 -y 0 -rely 0.033 -width 0 -relwidth 0.244 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.059 -y 0 -rely 0.127 -width 0 -relwidth 0.894 \
        -height 0 -relheight 0.13 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

