#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jul 13, 2021 11:30:50 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import arduino_uno_gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    arduino_uno_gui_support.set_Tk_var()
    top = TVeSmartAppTopLevel (root)
    arduino_uno_gui_support.init(root, top)
    root.mainloop()

w = None
def create_TVeSmartAppTopLevel(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_TVeSmartAppTopLevel(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    arduino_uno_gui_support.set_Tk_var()
    top = TVeSmartAppTopLevel (w)
    arduino_uno_gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_TVeSmartAppTopLevel():
    global w
    w.destroy()
    w = None

class TVeSmartAppTopLevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("340x315+376+189")
        top.minsize(120, 1)
        top.maxsize(3844, 1181)
        top.resizable(1,  1)
        top.title("TVeSmart switch")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.label_frame_dout = tk.LabelFrame(top)
        self.label_frame_dout.place(relx=0.029, rely=0.286, relheight=0.683
                , relwidth=0.938)
        self.label_frame_dout.configure(relief='groove')
        self.label_frame_dout.configure(foreground="black")
        self.label_frame_dout.configure(text='''Arduino Relay controller''')
        self.label_frame_dout.configure(background="#d4d4d4")
        self.label_frame_dout.configure(highlightbackground="#d9d9d9")
        self.label_frame_dout.configure(highlightcolor="black")

        self.button_do1 = tk.Button(self.label_frame_dout)
        self.button_do1.place(relx=0.752, rely=0.233, height=30, width=60
                , bordermode='ignore')
        self.button_do1.configure(activebackground="#d4d4d4")
        self.button_do1.configure(activeforeground="#000000")
        self.button_do1.configure(background="#d4d4d4")
        self.button_do1.configure(borderwidth="0")
        self.button_do1.configure(disabledforeground="#a3a3a3")
        self.button_do1.configure(foreground="#000000")
        self.button_do1.configure(highlightbackground="#d4d4d4")
        self.button_do1.configure(highlightcolor="black")
        self.button_do1.configure(pady="0")
        self.button_do1.configure(relief="flat")
        self.button_do1.configure(text='''do1''')

        self.button_do2 = tk.Button(self.label_frame_dout)
        self.button_do2.place(relx=0.752, rely=0.651, height=30, width=60
                , bordermode='ignore')
        self.button_do2.configure(activebackground="#d4d4d4")
        self.button_do2.configure(activeforeground="#000000")
        self.button_do2.configure(background="#d4d4d4")
        self.button_do2.configure(borderwidth="0")
        self.button_do2.configure(disabledforeground="#a3a3a3")
        self.button_do2.configure(foreground="#000000")
        self.button_do2.configure(highlightbackground="#d4d4d4")
        self.button_do2.configure(highlightcolor="black")
        self.button_do2.configure(pady="0")
        self.button_do2.configure(relief="flat")
        self.button_do2.configure(text='''do2''')

        self.entry_relay1 = tk.Entry(self.label_frame_dout)
        self.entry_relay1.place(relx=0.031, rely=0.233, height=30, relwidth=0.639
                , bordermode='ignore')
        self.entry_relay1.configure(background="#d4d4d4")
        self.entry_relay1.configure(disabledforeground="#a3a3a3")
        self.entry_relay1.configure(font="TkFixedFont")
        self.entry_relay1.configure(foreground="#000000")
        self.entry_relay1.configure(highlightbackground="#d9d9d9")
        self.entry_relay1.configure(highlightcolor="black")
        self.entry_relay1.configure(insertbackground="black")
        self.entry_relay1.configure(justify='center')
        self.entry_relay1.configure(selectbackground="blue")
        self.entry_relay1.configure(selectforeground="white")

        self.entry_relay2 = tk.Entry(self.label_frame_dout)
        self.entry_relay2.place(relx=0.031, rely=0.651, height=30, relwidth=0.639
                , bordermode='ignore')
        self.entry_relay2.configure(background="#d4d4d4")
        self.entry_relay2.configure(disabledforeground="#a3a3a3")
        self.entry_relay2.configure(font="TkFixedFont")
        self.entry_relay2.configure(foreground="#000000")
        self.entry_relay2.configure(highlightbackground="#d9d9d9")
        self.entry_relay2.configure(highlightcolor="black")
        self.entry_relay2.configure(insertbackground="black")
        self.entry_relay2.configure(justify='center')
        self.entry_relay2.configure(selectbackground="blue")
        self.entry_relay2.configure(selectforeground="white")

        self.button_com_port_open_close = tk.Button(top)
        self.button_com_port_open_close.place(relx=0.824, rely=0.032, height=24
                , width=47)
        self.button_com_port_open_close.configure(activebackground="#ececec")
        self.button_com_port_open_close.configure(activeforeground="#000000")
        self.button_com_port_open_close.configure(background="#008000")
        self.button_com_port_open_close.configure(disabledforeground="#a3a3a3")
        self.button_com_port_open_close.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.button_com_port_open_close.configure(foreground="#ffffff")
        self.button_com_port_open_close.configure(highlightbackground="#ffffff")
        self.button_com_port_open_close.configure(highlightcolor="#000000")
        self.button_com_port_open_close.configure(pady="0")
        self.button_com_port_open_close.configure(text='''OPEN''')

        self.label_com_port_selection = tk.Label(top)
        self.label_com_port_selection.place(relx=0.018, rely=0.032, height=22
                , width=114)
        self.label_com_port_selection.configure(activebackground="#f9f9f9")
        self.label_com_port_selection.configure(activeforeground="black")
        self.label_com_port_selection.configure(background="#ffffff")
        self.label_com_port_selection.configure(disabledforeground="#a3a3a3")
        self.label_com_port_selection.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.label_com_port_selection.configure(foreground="#000000")
        self.label_com_port_selection.configure(highlightbackground="#d9d9d9")
        self.label_com_port_selection.configure(highlightcolor="black")
        self.label_com_port_selection.configure(text='''select COM port''')

        self.combobox_com_port_list = ttk.Combobox(top)
        self.combobox_com_port_list.place(relx=0.382, rely=0.032, relheight=0.07
                , relwidth=0.244)
        self.combobox_com_port_list.configure(textvariable=arduino_uno_gui_support.combobox)
        self.combobox_com_port_list.configure(takefocus="")

        self.label_com_port_status_info = tk.Label(top)
        self.label_com_port_status_info.place(relx=0.059, rely=0.127, height=41
                , width=304)
        self.label_com_port_status_info.configure(activebackground="#ffffff")
        self.label_com_port_status_info.configure(activeforeground="black")
        self.label_com_port_status_info.configure(background="#ffffff")
        self.label_com_port_status_info.configure(disabledforeground="#a3a3a3")
        self.label_com_port_status_info.configure(foreground="#000000")
        self.label_com_port_status_info.configure(highlightbackground="#d9d9d9")
        self.label_com_port_status_info.configure(highlightcolor="black")
        self.label_com_port_status_info.configure(text='''Label''')

if __name__ == '__main__':
    vp_start_gui()





